import type { ThemeConfig } from "antd";

export const designTheme: ThemeConfig = {
  token: {
    colorPrimary: "#191919",
    colorPrimaryHover: "#333333",
    colorPrimaryActive: "#000000",
    colorInfo: "#2563EB",
    colorSuccess: "#1F8A4C",
    colorWarning: "#C46A17",
    colorError: "#D64545",
    colorBgLayout: "#F5F2EB",
    colorBgContainer: "#FBFAF5",
    colorBgElevated: "#FBFAF5",
    controlItemBgActive: "#E9E4D6",
    controlItemBgActiveHover: "#E2DCCB",
    colorBorder: "#E2DCCD",
    colorBorderSecondary: "#E2DCCD",
    colorText: "#37352F",
    colorTextHeading: "#191919",
    colorTextSecondary: "#787774",
    colorTextTertiary: "#A8A8A5",
    borderRadius: 10,
    borderRadiusLG: 12,
    borderRadiusSM: 8,
    fontFamily:
      'Inter, "PingFang SC", "Microsoft YaHei", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 14,
    lineHeight: 1.57,
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.04)",
    boxShadowSecondary: "0 4px 12px rgba(0, 0, 0, 0.06)",
    controlOutline: "transparent",
    motionDurationFast: "0.15s",
    motionDurationMid: "0.2s",
  },
  components: {
    Button: {
      borderRadius: 8,
      primaryShadow: "none",
      defaultShadow: "none",
    },
    Card: {
      borderRadiusLG: 12,
      boxShadow: "none",
      boxShadowTertiary: "none",
    },
    Input: {
      activeBorderColor: "#B5AB92",
      activeShadow: "none",
      hoverBorderColor: "#B5AB92",
    },
    Menu: {
      itemBg: "transparent",
      itemColor: "#787774",
      itemHoverBg: "#F0ECE1",
      itemHoverColor: "#191919",
      itemSelectedBg: "#E9E4D6",
      itemSelectedColor: "#191919",
      itemBorderRadius: 8,
    },
    Modal: {
      borderRadiusLG: 16,
    },
    Select: {
      activeBorderColor: "#B5AB92",
      activeOutlineColor: "transparent",
      hoverBorderColor: "#B5AB92",
      optionSelectedBg: "#E9E4D6",
      optionSelectedColor: "#191919",
      optionActiveBg: "#F0ECE1",
    },
    Table: {
      headerBg: "#F5F2EB",
      headerColor: "#787774",
      rowHoverBg: "#F0ECE1",
    },
  },
};
